image: golang:1.12

before_script:
- go version
- make setup
- make modules
- make generate

stages:
- test
- build

#lint:
#  stage: test
#  script:
#  - make lint

test:
  stage: test
  script:
  - AWS_REGION=us-west-2 AWS_ACCESS_KEY_ID=${aws_access_key_id} AWS_SECRET_ACCESS_KEY=${aws_secret_key_id} make test-all

build:
  stage: build
  script:
  - make build
